spring:
  datasource:
    url: jdbc:mysql://129.211.81.88:3306/growing_diary?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: PengZiHao1999.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 1340589637@qq.com
    password: cshuzmmbykhvhiai
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
          debug: true



